Styling
AlexLaviolette/frolfable pull request #4
Opened 2021-02-11 23:19 UTC by kravse

New layout changes. Not final but a baseline to work from. 

![Screen Shot 2021-02-11 at 3 45 54 PM](https://user-images.githubusercontent.com/3950963/107711396-96270a80-6c95-11eb-8f1b-b0c59a463737.png)

2021-02-11 23:21 UTC, AlexLaviolette requested changes
lgtm.

one small nit, looks like you left an unused var in there

2021-02-11 23:21 UTC, AlexLaviolette commented on backend/app.py
> +    counter = 0
seems unused?

2021-02-11 23:48 UTC, kravse commented on backend/app.py
> +    counter = 0
Shit sorry. I think I was testing something and forgot to remove 🤕

2021-02-12 01:43 UTC, AlexLaviolette approved these changes

2021-02-12 15:48 UTC, merged